### ISSUE TITLE
Commands not visible

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/XpandPosh#6]
Hi,

after installing Version 0.7.1 the commands are not visible. F.e. the
Get-Command -Module XpandPwsh
doesn´t work anymore.

It seems that it is installed but not registered.

![png1](https://user-images.githubusercontent.com/43132306/59658246-5dbee880-91a3-11e9-9005-4d91950c2e19.PNG)

**Comment by apobekiaris** [comment]
see #5 

this is a powershell core module now and from your shot i see you install it as powershell5 not sure how u manage to do it as there is a requirement to powershell 6

https://github.com/eXpandFramework/XpandPwsh/blob/bbf0196f07cbcb87e0a32f0afe5771e3a99eacf5/XpandPwsh/XpandPwsh.psd1#L36

remove and install again from a pwsh prompt 

install pwsh from choco if u want like

```ps1
choco install pwsh
```

**Comment by apobekiaris** [comment]
see also https://docs.microsoft.com/en-us/powershell/scripting/powershell-support-lifecycle?view=powershell-6#windows-powershell-module

or even you can try a manual always working approach to add all your custom modules in path by modifying your profile.ps1, here how it looks in my machine

```ps1
#custom locations
$customModulePaths=@(
    "C:\Dropbox\PSModules",
    "C:\Program Files (x86)\Microsoft SQL Server\140\Tools\PowerShell\Modules\",
    "C:\Work\eXpandFramework\XpandPwsh",
    "C:\Work\eXpandFramework\platyPS\src\"
) -join ";"
$Env:PSModulePath+=";$customModulePaths"
$Env:PSModulePath=(($Env:PSModulePath -split ";")|Get-Unique) -join ";"

```

**Comment by apobekiaris** [comment]
I relaxed this requirement in 0.8.0

#7

**Comment by CWolffIF** [comment]
Top
